systems:
  - id: mcp-test
    documentation:
      - id: docs-fs
        type: html
        options:
          selector: main
        extractor:
          type: fs
          options:
            path: ./e2e/_input/mcp/
          include:
            - "docs/**/*.html"
      - id: docs-http
        type: html
        options:
          selector: main
        extractor:
          type: http
          options:
            baseUrl: http://127.0.0.1:8081/
            start: "./docs"
          include:
            - "docs/**/*"
      - id: docs-ssh
        type: md
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - "**/*.md"
      - id: docs-http-git
        type: md
        extractor:
          type: git
          options:
            repo: https://github.com/appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: http
              options:
                username: git
                password: ${HYALINE_GITHUB_PAT}
          include:
            - "**/*.md"