github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: my-app
    code:
      - id: app-ssh1
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - package.json
            - "**/*.js"
          exclude:
            - "**/*.test.js"
      - id: app-ssh2
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - package.json
            - "**/*.js"
          exclude:
            - "**/*.test.js"
    documentation:
      - id: md-ssh1
        type: md
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - "**/*.md"
      - id: md-ssh2
        type: md
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - "**/*.md"