llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${ANTHROPIC_KEY}

systems:
  - id: local
    code:
      - id: app
        extractor: fs
        path: ./_example/
        preset: js
    docs:
      - id: docs
        type: md
        extractor: fs
        path: ./_example/
        glob: ./**/*.md
    checks:
      - id: run-locally
        description: Ensure that instructions on how to run the system locally for development exist. 
        rule: section-exists
        options:
          document: README.md
          section: Running Locally
          severity: ERROR
          allowTodos: false