llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${ANTHROPIC_KEY}

systems:
  - id: local
    code:
      - id: app
        extractor: fs
        fs:
          path: ./_example/
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: md-docs
        type: md
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.md"
      - id: html-docs
        type: html
        html:
          selector: main
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.html"
    checks:
      - id: run-locally
        description: Ensure that instructions on how to run the system locally for development exist. 
        rule: section-exists
        options:
          document: README.md
          section: Running Locally
          severity: ERROR
          allowTodos: false
  - id: git
    code:
      - id: app-ssh
        extractor: git
        git:
          # repo: git@github.com:appgardenstudios/hyaline-example.git
          path: ../../hyaline-example/
          branch: main
          # clone: false
          # fetch: false
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"