llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${HYALINE_ANTHROPIC_KEY}

systems:
  - id: local
    code:
      - id: app
        extractor: fs
        fs:
          path: ./_example/
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: md-docs
        type: md
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.md"
      - id: html-docs
        type: html
        html:
          selector: main
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.html"
    checks:
      - id: run-locally
        description: Ensure that instructions on how to run the system locally for development exist. 
        rule: section-exists
        options:
          document: README.md
          section: Running Locally
          severity: ERROR
          allowTodos: false
  - id: git
    code:
      - id: app-path
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-ssh
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-http
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: md-path
        type: md
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - "**/*.md"
      - id: md-ssh
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - "**/*.md"
      - id: md-http
        type: md
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - "**/*.md"