llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${HYALINE_ANTHROPIC_KEY}

github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: local
    code:
      - id: app
        extractor: fs
        fs:
          path: ./_example/
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: md-docs
        type: md
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.md"
      - id: html-docs
        type: html
        html:
          selector: main
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.html"
    checks:
      - id: run-locally
        description: Ensure that instructions on how to run the system locally for development exist. 
        rule: section-exists
        options:
          document: README.md
          section: Running Locally
          severity: ERROR
          allowTodos: false
  - id: git
    code:
      - id: app-path
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-ssh
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-http
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: md-path
        type: md
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - "**/*.md"
      - id: md-ssh
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - "**/*.md"
      - id: md-http
        type: md
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - "**/*.md"
  - id: http
    docs:
      - id: http-docs-base
        type: html
        html:
          selector: main
        extractor: http
        http:
          baseUrl: http://localhost:8080/docs
        include:
          - "**/*"
        exclude:
          - "irrelevant"
      - id: http-docs-start
        type: html
        html:
          selector: main
        extractor: http
        http:
          baseUrl: http://localhost:8080/
          start: "./docs"
        include:
          - "docs/**/*"
        exclude:
          - "docs/irrelevant"
  - id: generate-config
    docs:
      - id: md-docs
        type: md
        extractor: fs
        fs:
          path: ./_example/
        include:
          - "**/*.md"
        rules: ["basic-repo"]
  - id: check-change
    code:
      - id: app
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: app
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - "**/*.md"
        rules: [check-change]

rules:
  - id: basic-repo
    documents:
      - path: README.md
        purpose: The purpose of the document
        required: true
        sections:
          - id: Example
            purpose: The purpose of the section
            sections:
              - id: Subsection 1
                ignore: true
          - id: Running Locally
            required: true
  - id: check-change
    documents:
      - path: docs/docsDoc.md
        purpose: The docs/docsDoc.md file appears to be a test document used to verify basic document formatting and functionality. It contains simple test content and repeated test phrases.
        required: true
        sections:
          - id: This is a test
            purpose: This section demonstrates basic test content through repetitive test phrases, serving as a simple verification of document formatting and display capabilities.
            required: true
      - path: docs/preDoc.md
        purpose: The document docs/preDoc.md appears to be a markdown file containing preliminary text and a sample heading section with placeholder content. Its purpose seems to be demonstrating document structure rather than providing actual documentation content.
        required: true
        sections:
          - id: A Random Heading
            purpose: This placeholder section contains sample text to demonstrate document structure and formatting, aligning with the preliminary nature of the preDoc.md file.
            required: true
      - path: README.md
        purpose: The purpose of the document
        required: true
        sections:
          - id: Example
            purpose: The purpose of the section
            sections:
              - id: Subsection 1
                ignore: true
              - id: Subsection 2
                purpose: Since this appears to be placeholder content without specific details, I can only state that this section titled "Subsection 2" is a component of the README.md document that supports its overall purpose of "The purpose of the document."
                required: true
          - id: Running Locally
            required: true
