// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

type DOCUMENT struct {
	ID            string
	SourceID      string
	Type          string
	Purpose       string
	RawData       string
	ExtractedData string
}

type DOCUMENTTAG struct {
	SourceID   string
	DocumentID string
	TagKey     string
	TagValue   string
}

type SECTION struct {
	ID            string
	DocumentID    string
	SourceID      string
	ParentID      string
	PeerOrder     interface{}
	Name          string
	Purpose       string
	ExtractedData string
}

type SECTIONTAG struct {
	SourceID   string
	DocumentID string
	SectionID  string
	TagKey     string
	TagValue   string
}

type SOURCE struct {
	ID          string
	Description string
	Crawler     string
	Root        string
}
