// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

type Document struct {
	ID            string
	SourceID      string
	Type          string
	Purpose       string
	RawData       string
	ExtractedData string
}

type DocumentTag struct {
	SourceID   string
	DocumentID string
	TagKey     string
	TagValue   string
}

type Section struct {
	ID            string
	DocumentID    string
	SourceID      string
	ParentID      string
	PeerOrder     interface{}
	Name          string
	ExtractedData string
}

type SectionTag struct {
	SourceID   string
	DocumentID string
	SectionID  string
	TagKey     string
	TagValue   string
}

type Source struct {
	ID          string
	Description string
	Crawler     string
	Root        string
}
