systems:
  - id: my-app
    code:
      - id: app
        extractor: fs
        fs:
          path: ./_input/extract-current/
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: docs
        type: md
        extractor: fs
        fs:
          path: ./_input/extract-current/
        include:
          - "**/*.md"