github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: git
    code:
      - id: app-ssh
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    documentation:
      - id: app-ssh
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - "**/*.md"
