github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: git
    code:
      - id: app-path
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-ssh
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-http
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-code-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    docs:
      - id: app-path
        type: md
        extractor: git
        git:
          path: ../../hyaline-example/
          branch: main
        include:
          - "**/*.md"
      - id: app-ssh
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-ssh
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
            password: ${HYALINE_SSH_PASSWORD}
        include:
          - "**/*.md"
      - id: app-http
        type: md
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          # path: /Users/johnmclark/code/hyaline-docs-http
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - "**/*.md"
