llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${ANTHROPIC_KEY}

systems:
  - id: my-app
    code:
      - id: app-fs
        extractor:
          type: fs
          options:
            path: ./
          include:
            - package.json
            - "./**/*.js"
          exclude:
            - "./**/*.test.js"
      - id: app-git-http
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: http
              options:
                username: bob
                password: nope
          include:
            - package.json
            - "./**/*.js"
          exclude:
            - "./**/*.test.js"
      - id: app-git-ssh
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: ssh
              options:
                user: bob
                pem: my-pem
                password: nope
          include:
            - package.json
            - "./**/*.js"
          exclude:
            - "./**/*.test.js"
    documentation:
      - id: md-docs-fs
        type: md
        extractor:
          type: fs
          options:
            path: ./
          include: 
            - ./**/*.md
      - id: md-docs-git-http
        type: md
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: http
              options:
                username: bob
                password: nope
          include: 
            - ./**/*.md
      - id: md-docs-git-ssh
        type: md
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: ssh
              options:
                user: bob
                pem: my-pem
                password: nope
          include: 
            - ./**/*.md
      - id: html-docs-fs
        type: html
        html:
          selector: main
        extractor:
          type: fs
          options:
            path: ./
          include: 
            - ./**/*.md
      - id: html-docs-git-http
        type: html
        html:
          selector: main
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: http
              options:
                username: bob
                password: nope
          include: 
            - ./**/*.md
      - id: html-docs-git-ssh
        type: html
        html:
          selector: main
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: main
            path: my/path
            clone: true
            auth:
              type: ssh
              options:
                user: bob
                pem: my-pem
                password: nope
          include: 
            - ./**/*.md
