llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  key: ${ANTHROPIC_KEY}

systems:
  - id: my-app
    code:
      - id: app
        extractor: fs
        fs:
          path: ./
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          path: my/path
          clone: true
          httpAuth:
            username: bob
            password: nope
          sshAuth:
            user: bob
            pem: my-pem
            password: nope
        include:
          - package.json
          - "./**/*.js"
        exclude:
          - "./**/*.test.js"
    documentation:
      - id: md-docs
        type: md
        extractor: fs
        fs:
          path: ./
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          path: my/path
          clone: true
          httpAuth:
            username: bob
            password: nope
          sshAuth:
            user: bob
            pem: my-pem
            password: nope
        include: 
         - ./**/*.md
      - id: html-docs
        type: html
        html:
          selector: main
        extractor: fs
        fs:
          path: ./
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          path: my/path
          clone: true
          httpAuth:
            username: bob
            password: nope
          sshAuth:
            user: bob
            pem: my-pem
            password: nope
        include: 
         - ./**/*.md
