baseURL = 'https://www.hyaline.dev/'
languageCode = 'en-us'
title = 'Hyaline'
disableKinds = ['taxonomy', 'term']
# Enabling GitInfo allows the use of git information in the site (e.g. last modified date)
enableGitInfo = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    includeFiles = ['/documentation/**.svg','/documentation/**.png', '/articles/**.svg','/articles/**.png']
    source = 'content'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables HTML rendering from Markdown files
      unsafe = true