llm:
  provider: anthropic
  model: claude-sonnet-4-20250514
  key: ${HYALINE_ANTHROPIC_KEY}

github:
  token: ${HYALINE_GITHUB_PATS}

systems:
  - id: url-shortener
    code:
      - id: app
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: url-shortener
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - "url-shortener/**/*.js"
          exclude:
            - "**/node_modules/**"
            - "**/*.test.js"
    documentation:
      - id: external
        type: html
        extractor:
          type: git
          options:
            repo: git@github.com:appgardenstudios/hyaline-example.git
            branch: url-shortener
            clone: true
            auth:
              type: ssh
              options:
                user: git
                pem: ${HYALINE_SSH_PEM}
          include:
            - "url-shortener/**/*.html"
          exclude:
            - "**/node_modules/**"
        documents:
          - name: url-shortener/public/documentation.html
            purpose: Customer-facing documentation about URL shortener features.
            required: true
            sections:
              - name: URL Shortener Documentation
                purpose: Provides an overview of the URL shortener, along with how it works and its features
                required: true
                sections:
                  - name: What is URL Shortener?
                    purpose: Describes what a URL shortener does, how it works, and warn the user about the potential adverse effects from shortening a URL
                    required: true
                  - name: How to Use URL Shortener
                    purpose: Step-by-step instructions for using the service
                    required: true
                  - name: Features
                    purpose: Lists the features available to users
                    required: true
                  - name: Privacy & Security
                    purpose: Explains privacy and security considerations
                    required: true