llm:
  provider: testing
  model: test
  key: test

github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: generate-config
    documentation:
      - id: md-docs
        type: md
        extractor:
          type: fs
          options:
            path: ./_example/
          include:
            - "**/*.md"
        includeDocuments: ["basic-repo"]

commonDocuments:
  - id: basic-repo
    documents:
      - name: README.md
        purpose: The purpose of the document
        required: true
        sections:
          - name: Example
            purpose: The purpose of the section
            sections:
              - name: Subsection 1
                ignore: true
          - name: Running Locally
            required: true