llm:
  provider: testing
  model: test
  key: test

github:
  token: ${HYALINE_GITHUB_PAT}

systems:
  - id: generate-config
    documentation:
      - id: md-docs
        type: md
        extractor:
          type: fs
          options:
            path: ./_example/
          include:
            - "**/*.md"
        rules: ["basic-repo"]

rules:
  - id: basic-repo
    documents:
      - path: README.md
        purpose: The purpose of the document
        required: true
        sections:
          - id: Example
            purpose: The purpose of the section
            sections:
              - id: Subsection 1
                ignore: true
          - id: Running Locally
            required: true