commonDocuments:
    - id: md-docs
      documents:
        - name: docs/docsDoc.md
          required: true
        - name: docs/preDoc.md
          required: true
        - name: README.md
          purpose: The purpose of the document
          required: true
