rules:
    - id: md-docs
      documents:
        - path: README.md
          purpose: The purpose of the document
          required: true
          sections:
            - id: Example
              purpose: The purpose of the section
              sections:
                - id: Subsection 1
                  ignore: true
                - id: Subsection 2
            - id: Running Locally
              required: true
        - path: docs/docsDoc.md
          required: true
          sections:
            - required: true
              sections:
                - id: This is a test
                  required: true
        - path: docs/preDoc.md
          required: true
          sections:
            - required: true
              sections:
                - id: A Random Heading
                  required: true
