commonDocuments:
    - id: md-docs
      documents:
        - name: docs/docsDoc.md
          required: true
          sections:
            - name: This is a test
              required: true
        - name: docs/preDoc.md
          required: true
          sections:
            - name: A Random Heading
              required: true
        - name: README.md
          purpose: The purpose of the document
          required: true
          sections:
            - name: Example
              purpose: The purpose of the section
              sections:
                - name: Subsection 1
                  ignore: true
                - name: Subsection 2
                  required: true
            - name: Running Locally
              required: true
