systems:
  - id: my-app
    code:
      - id: app-ssh
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
      - id: app-http
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - package.json
          - "**/*.js"
        exclude:
          - "**/*.test.js"
    documentation:
      - id: md-ssh
        type: md
        extractor: git
        git:
          repo: git@github.com:appgardenstudios/hyaline-example.git
          branch: main
          clone: true
          sshAuth:
            user: git
            pem: ${HYALINE_SSH_PEM}
        include:
          - "**/*.md"
      - id: md-http
        type: md
        extractor: git
        git:
          repo: https://github.com/appgardenstudios/hyaline-example.git
          branch: main
          clone: true
          httpAuth:
            username: git
            password: ${HYALINE_GITHUB_PAT}
        include:
          - "**/*.md"