systems:
  - id: my-app
    documentation:
      - id: http-docs
        type: html
        options:
          selector: main
        extractor:
          type: http
          options:
            baseUrl: http://127.0.0.1:8081/
            start: "./docs"
          include:
            - "docs/**/*"
          exclude:
            - "docs/irrelevant.html"