systems:
  - id: my-app
    documentation:
      - id: http-docs
        type: html
        html:
          selector: main
        extractor: http
        http:
          baseUrl: http://127.0.0.1:8081/
          start: "./docs"
        include:
          - "docs/**/*"
        exclude:
          - "docs/irrelevant.html"