on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test-github-models:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      models: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build Hyaline
        run: |
          cd cli
          make build
      - name: Check PR
        run: |
          cd cli
          ./hyaline check pr --config ../.vscode/hyaline/check-pr-openai/test_github_models.yml --pull-request ${{ github.repository }}/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}